spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://localhost:8081
          predicates:
            - Path=/reservations/**
        - id: payments
          uri: http://localhost:8082
          predicates:
            - Path=/payments/**
        - id: rooms
          uri: http://localhost:8083
          predicates:
            - Path=/rooms/**
        - id: notices
          uri: http://localhost:8084
          predicates:
            - Path=/notices/**
        - id: roomInfoes
          uri: http://localhost:8085
          predicates:
            - Path=/roomInfoes/**
        - id: promotionManagement
          uri: http://localhost:8086
          predicates:
            - Path=/promotions/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://reservation:8081
          predicates:
            - Path=/reservations/**
        - id: payments
          uri: http://payments:8082
          predicates:
            - Path=/payments/**
        - id: rooms
          uri: http://rooms:8083
          predicates:
            - Path=/rooms/**
        - id: notices
          uri: http://notices:8084
          predicates:
            - Path=/notices/**
        - id: roomInfoes
          uri: http://roomInfoes:8085
          predicates:
            - Path=/roomInfoes/**
        - id: promotionmanagement
          uri: http://promotion:8086
          predicates:
            - Path=/promotions/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
